
# try:
#     print(x)
# except NameError:
#     print("Variable x is not defined")
# except:
#     print("An exception occurred")
    
try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")